# Generated by Django 4.1.3 on 2023-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipaddress", models.CharField(max_length=100)),
                ("date_visited", models.DateField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("times_views", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
