# Generated by Django 4.1.3 on 2023-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0002_analytics_delete_visitor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analytics",
            options={"verbose_name_plural": "Analytics"},
        ),
        migrations.AlterField(
            model_name="analytics",
            name="date_visited",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
