# Generated by Django 4.1.3 on 2023-04-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0003_alter_analytics_options_alter_analytics_date_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="time_visited",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analytics",
            name="date_visited",
            field=models.DateField(auto_now_add=True),
        ),
    ]
