# Generated by Django 4.1.3 on 2023-04-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0004_analytics_time_visited_alter_analytics_date_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="device_brand",
            field=models.CharField(default="Apple", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="device_family",
            field=models.CharField(default="Apple", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="device_model",
            field=models.CharField(default="iphone", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analytics",
            name="is_mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analytics",
            name="is_pc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analytics",
            name="is_tablet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analytics",
            name="is_touch_capable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analytics",
            name="os_family",
            field=models.CharField(default="windows", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="os_version",
            field=models.CharField(default=2.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analytics",
            name="os_version_string",
            field=models.CharField(default=1.2, max_length=200),
            preserve_default=False,
        ),
    ]
