# Generated by Django 4.1.3 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0005_analytics_device_brand_analytics_device_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="browser_family",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="analytics",
            name="browser_version",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="analytics",
            name="browser_version_string",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="device_brand",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="device_family",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="device_model",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="os_family",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="os_version",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="os_version_string",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
