# Generated by Django 4.1.3 on 2023-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Analytics",
            "0006_analytics_browser_family_analytics_browser_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="user",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
