# Generated by Django 4.1.3 on 2023-04-13 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "OurServices",
            "0004_alter_carrental_options_alter_carrentalimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrental",
            name="contact_no",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                        regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contactusforenquires",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                        regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="letussellyourcar",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                        regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentcar",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                        regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shipcarforussell",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                        regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                    )
                ],
            ),
        ),
    ]
