# Generated by Django 4.1.3 on 2023-04-18 08:37

import OurServices.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OurServices", "0005_alter_carrental_contact_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListDrivingSch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("driving_sch_name", models.CharField(max_length=100)),
                ("services_offered", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("approved", models.BooleanField(default=False)),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                                regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, editable=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("VOLTA ", "VOLTA "),
                            ("BRONG AHAFO ", "BRONG AHAFO "),
                            ("OTI ", "OTI "),
                            ("CENTRAL ", "CENTRAL "),
                            ("EASTERN ", "EASTERN "),
                            ("GREATER ACCRA ", "GREATER ACCRA "),
                            ("NORTH EAST ", "NORTH EAST "),
                            ("NORTHERN ", "NORTHERN "),
                            ("SAVANNAH ", "SAVANNAH "),
                            ("UPPER EAST ", "UPPER EAST "),
                            ("UPPER WEST ", "UPPER WEST "),
                            ("WESTERN ", "WESTERN "),
                            ("WESTERN NORTH ", "WESTERN NORTH "),
                            ("BONO EAST  ", "BONO EAST  "),
                            ("AHAFO ", "AHAFO "),
                            ("ASHANTI ", "ASHANTI "),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestDrivingSch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("approved", models.BooleanField(default=False)),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                                regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, editable=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("VOLTA ", "VOLTA "),
                            ("BRONG AHAFO ", "BRONG AHAFO "),
                            ("OTI ", "OTI "),
                            ("CENTRAL ", "CENTRAL "),
                            ("EASTERN ", "EASTERN "),
                            ("GREATER ACCRA ", "GREATER ACCRA "),
                            ("NORTH EAST ", "NORTH EAST "),
                            ("NORTHERN ", "NORTHERN "),
                            ("SAVANNAH ", "SAVANNAH "),
                            ("UPPER EAST ", "UPPER EAST "),
                            ("UPPER WEST ", "UPPER WEST "),
                            ("WESTERN ", "WESTERN "),
                            ("WESTERN NORTH ", "WESTERN NORTH "),
                            ("BONO EAST  ", "BONO EAST  "),
                            ("AHAFO ", "AHAFO "),
                            ("ASHANTI ", "ASHANTI "),
                        ],
                        max_length=100,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ListCarRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per",
                    models.CharField(
                        choices=[
                            ("Per Hour", "Per Hour"),
                            ("Per Day", "Per Day"),
                            ("Per Week", "Per Week"),
                            ("Per Month", "Per Month"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                                regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                            )
                        ],
                    ),
                ),
                ("color", models.CharField(max_length=100)),
                ("interior_color", models.CharField(max_length=100)),
                ("accessories", models.TextField()),
                (
                    "main_image",
                    models.ImageField(upload_to=OurServices.models.rental_path),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("VOLTA ", "VOLTA "),
                            ("BRONG AHAFO ", "BRONG AHAFO "),
                            ("OTI ", "OTI "),
                            ("CENTRAL ", "CENTRAL "),
                            ("EASTERN ", "EASTERN "),
                            ("GREATER ACCRA ", "GREATER ACCRA "),
                            ("NORTH EAST ", "NORTH EAST "),
                            ("NORTHERN ", "NORTHERN "),
                            ("SAVANNAH ", "SAVANNAH "),
                            ("UPPER EAST ", "UPPER EAST "),
                            ("UPPER WEST ", "UPPER WEST "),
                            ("WESTERN ", "WESTERN "),
                            ("WESTERN NORTH ", "WESTERN NORTH "),
                            ("BONO EAST  ", "BONO EAST  "),
                            ("AHAFO ", "AHAFO "),
                            ("ASHANTI ", "ASHANTI "),
                        ],
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True, editable=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.list_rental_images_path,
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.list_rental_images_path,
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.list_rental_images_path,
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.list_rental_images_path,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Car Rentals",
            },
        ),
        migrations.CreateModel(
            name="ListAccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "main_image",
                    models.ImageField(upload_to=OurServices.models.accessories_path),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(blank=True, editable=False, null=True)),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed.",
                                regex="^\\+?[0-9]{1,3}?\\s?\\-?[0-9]{1,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("VOLTA ", "VOLTA "),
                            ("BRONG AHAFO ", "BRONG AHAFO "),
                            ("OTI ", "OTI "),
                            ("CENTRAL ", "CENTRAL "),
                            ("EASTERN ", "EASTERN "),
                            ("GREATER ACCRA ", "GREATER ACCRA "),
                            ("NORTH EAST ", "NORTH EAST "),
                            ("NORTHERN ", "NORTHERN "),
                            ("SAVANNAH ", "SAVANNAH "),
                            ("UPPER EAST ", "UPPER EAST "),
                            ("UPPER WEST ", "UPPER WEST "),
                            ("WESTERN ", "WESTERN "),
                            ("WESTERN NORTH ", "WESTERN NORTH "),
                            ("BONO EAST  ", "BONO EAST  "),
                            ("AHAFO ", "AHAFO "),
                            ("ASHANTI ", "ASHANTI "),
                        ],
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.lists_accessories_images_path,
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.lists_accessories_images_path,
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.lists_accessories_images_path,
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=OurServices.models.lists_accessories_images_path,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List Accessories",
            },
        ),
    ]
