# Generated by Django 4.1.3 on 2023-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OurServices", "0006_listdrivingsch_requestdrivingsch_listcarrental_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listaccessories",
            name="user",
        ),
        migrations.RemoveField(
            model_name="listcarrental",
            name="user",
        ),
        migrations.AddField(
            model_name="requestdrivingsch",
            name="anything_else",
            field=models.TextField(default="fsf"),
            preserve_default=False,
        ),
    ]
