# Generated by Django 4.1.3 on 2023-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OurServices", "0007_remove_listaccessories_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestdrivingsch",
            name="anything_else",
            field=models.TextField(blank=True, null=True),
        ),
    ]
