# Generated by Django 4.1.3 on 2023-04-05 09:22

import Cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0002_remove_car_doors_num_remove_car_engine_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="contact_no",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+233552229122'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="main_image",
            field=models.ImageField(upload_to=Cars.models.car_path),
        ),
        migrations.AlterField(
            model_name="car",
            name="year_manufactured",
            field=Cars.models.YearField(max_length=4),
        ),
        migrations.AlterField(
            model_name="carenquiry",
            name="contact_no",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+233552229122'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(upload_to=Cars.models.car_images_path),
        ),
    ]
