# Generated by Django 4.1.3 on 2023-04-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0003_alter_car_contact_no_alter_car_main_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carenquiry",
            options={"verbose_name_plural": "Car Enquires"},
        ),
        migrations.AlterModelOptions(
            name="carimage",
            options={"verbose_name_plural": "Car Images"},
        ),
    ]
