# Generated by Django 4.1.3 on 2023-03-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accessories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoriesenquiry",
            name="attended_to",
            field=models.BooleanField(default=False),
        ),
    ]
