# Generated by Django 4.1.3 on 2023-04-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accessories", "0004_alter_accessories_contact_no_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessories",
            options={"verbose_name_plural": "Accessories"},
        ),
        migrations.AlterModelOptions(
            name="accessoriesenquiry",
            options={"verbose_name_plural": "Accessory Enquires"},
        ),
        migrations.AlterModelOptions(
            name="accessoriesimages",
            options={"verbose_name_plural": "Accessory Images"},
        ),
    ]
