from django.db import models
from django.utils.text import slugify
from custom.custom_func import unique_slugify
from Authentication.models import User
from django.core.validators import RegexValidator
import os
from datetime import datetime

class YearField(models.CharField):
    default_validators = [RegexValidator(r'^\d{4}$', 'Enter a valid year.')]

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 4
        super().__init__(*args, **kwargs)



 


CarModelsAndMakes = [
    (
        "ACURA",
        (
            ("Acura ILX", "Acura ILX"),
            ("Acura TLX", "Acura TLX"),
            ("Acura RLX", "Acura RLX"),
            ("Acura NSX", "Acura NSX"),
            ("Acura RDX", "Acura RDX"),
            ("Acura MDX", "Acura MDX"),
        ),
    ),
    (
        "AUDI",
        (
            ("Audi A1", "Audi A1"),
            ("Audi A3", "Audi A3"),
            ("Audi A4", "Audi A4"),
            ("Audi A5", "Audi A5"),
            ("Audi A6", "Audi A6"),
            ("Audi A7", "Audi A7"),
            ("Audi A8", "Audi A8"),
            ("Audi Q2", "Audi Q2"),
            ("Audi Q3", "Audi Q3"),
            ("Audi Q5", "Audi Q5"),
            ("Audi Q7", "Audi Q7"),
            ("Audi Q8", "Audi Q8"),
            ("Audi TT", "Audi TT"),
            ("Audi R8", "Audi R8"),
            ("Audi E-TRON", "Audi E-TRON"),
        ),
    ),
    (
        "BMW",
        (
            ("BMW 1 Series", "BMW 1 Series"),
            ("BMW 2 Series", "BMW 2 Series"),
            ("BMW 3 Series", "BMW 3 Series"),
            ("BMW 4 Series", "BMW 4 Series"),
            ("BMW 5 Series", "BMW 5 Series"),
            ("BMW 6 Series", "BMW 6 Series"),
            ("BMW 7 Series", "BMW 7 Series"),
            ("BMW X1", "BMW X1"),
            ("BMW X2", "BMW X2"),
            ("BMW X3", "BMW X3"),
            ("BMW X4", "BMW X4"),
            ("BMW X5", "BMW X5"),
            ("BMW X6", "BMW X6"),
            ("BMW X7", "BMW X7"),
            ("BMW Z4", "BMW Z4"),
            ("BMW i3", "BMW i3"),
            ("BMW i8", "BMW i8"),
        ),
    ),
    (
        "BENTLEY",
        (
            ("Bentley Arnage", "Bentley Arnage"),
            ("Bentley Azure", "Bentley Azure"),
            ("Bentley Bentayga", "Bentley Bentayga"),
            ("Bentley Brooklands", "Bentley Brooklands"),
            ("Bentley Continental GT", "Bentley Continental GT"),
            ("Bentley Continental Flying Spur", "Bentley Continental Flying Spur"),
            ("Bentley Continental Supersports", "Bentley Continental Supersports"),
            ("Bentley Mulsanne", "Bentley Mulsanne"),
            ("Bentley Turbo R", "Bentley Turbo R"),
            ("Bentley Turbo S", "Bentley Turbo S"),
        ),
    ),
    (
        "BUICK",
        (
            ("Buick Cascada", "Buick Cascada"),
            ("Buick Enclave", "Buick Enclave"),
            ("Buick Encore", "Buick Encore"),
            ("Buick Encore GX", "Buick Encore GX"),
            ("Buick LaCrosse", "Buick LaCrosse"),
            ("Buick Regal", "Buick Regal"),
            ("Buick Verano", "Buick Verano"),
            ("Buick Century", "Buick Century"),
            ("Buick Electra", "Buick Electra"),
            ("Buick LeSabre", "Buick LeSabre"),
            ("Buick Lucerne", "Buick Lucerne"),
            ("Buick Park Avenue", "Buick Park Avenue"),
            ("Buick Rainier", "Buick Rainier"),
            ("Buick Reatta", "Buick Reatta"),
            ("Buick Rendezvous", "Buick Rendezvous"),
            ("Buick Riviera", "Buick Riviera"),
            ("Buick Roadmaster", "Buick Roadmaster"),
            ("Buick Skylark", "Buick Skylark"),
            ("Buick Special", "Buick Special"),
            ("Buick Terraza", "Buick Terraza"),
        ),
    ),
    (
        "CADILLAC",
        (
            ("Cadillac ATS", "Cadillac ATS"),
            ("Cadillac CT4", "Cadillac CT4"),
            ("Cadillac CT5", "Cadillac CT5"),
            ("Cadillac CTS", "Cadillac CTS"),
            ("Cadillac DTS", "Cadillac DTS"),
            ("Cadillac Eldorado", "Cadillac Eldorado"),
            ("Cadillac ELR", "Cadillac ELR"),
            ("Cadillac Escalade", "Cadillac Escalade"),
            ("Cadillac SRX", "Cadillac SRX"),
            ("Cadillac STS", "Cadillac STS"),
            ("Cadillac XLR", "Cadillac XLR"),
            ("Cadillac XT4", "Cadillac XT4"),
            ("Cadillac XT5", "Cadillac XT5"),
            ("Cadillac XT6", "Cadillac XT6"),
        ),
    ),
    (
        "CHEVROLET",
        (
            ("Chevrolet Bolt EV", "Chevrolet Bolt EV"),
            ("Chevrolet Camaro", "Chevrolet Camaro"),
            ("Chevrolet Colorado", "Chevrolet Colorado"),
            ("Chevrolet Corvette", "Chevrolet Corvette"),
            ("Chevrolet Cruze", "Chevrolet Cruze"),
            ("Chevrolet Equinox", "Chevrolet Equinox"),
            ("Chevrolet Express", "Chevrolet Express"),
            ("Chevrolet Impala", "Chevrolet Impala"),
            ("Chevrolet Malibu", "Chevrolet Malibu"),
            ("Chevrolet Silverado", "Chevrolet Silverado"),
            ("Chevrolet Sonic", "Chevrolet Sonic"),
            ("Chevrolet Spark", "Chevrolet Spark"),
            ("Chevrolet Suburban", "Chevrolet Suburban"),
            ("Chevrolet Tahoe", "Chevrolet Tahoe"),
            ("Chevrolet Traverse", "Chevrolet Traverse"),
            ("Chevrolet Blazer", "Chevrolet Blazer"),
            ("Chevrolet Trax", "Chevrolet Trax"),
            ("Chevrolet Blazer", "Chevrolet Blazer"),
            ("Chevrolet Trailblazer", "Chevrolet Trailblazer"),
            ("Chevrolet Cavalier", "Chevrolet Cavalier"),
            ("Chevrolet Celebrity", "Chevrolet Celebrity"),
            ("Chevrolet Citation", "Chevrolet Citation"),
            ("Chevrolet Classic", "Chevrolet Classic"),
            ("Chevrolet Colbat", "Chevrolet Colbat"),
            ("Chevrolet Corsica", "Chevrolet Corsica"),
            ("Chevrolet HHR", "Chevrolet HHR"),
            ("Chevrolet Lumina", "Chevrolet Lumina"),
            ("Chevrolet Monte Carlo", "Chevrolet Monte Carlo"),
            ("Chevrolet Nova", "Chevrolet Nova"),
        ),
    ),
    (
        "CHRYSLER",
        (
            ("Chrysler 200", "Chrysler 200"),
            ("Chrysler 300", "Chrysler 300"),
            ("Chrysler Pacifica", "Chrysler Pacifica"),
            ("Chrysler PT Cruiser", "Chrysler PT Cruiser"),
            ("Chrysler Sebring", "Chrysler Sebring"),
            ("Chrysler Town", "Chrysler Town"),
            ("Chrysler Aspen", "Chrysler Aspen"),
            ("Chrysler Crossfire", "Chrysler Crossfire"),
            ("Chrysler Concorde", "Chrysler Concorde"),
            ("Chrysler LHS", "Chrysler LHS"),
            ("Chrysler New Yorker", "Chrysler New Yorker"),
            ("Chrysler Voyager", "Chrysler Voyager"),
            ("Chrysler Imperial", "Chrysler Imperial"),
        ),
    ),
    (
        "DATSUN",
        (
            ("Datsun 210", "Datsun 210"),
            ("Datsun 240Z", "Datsun 240Z"),
            ("Datsun 260Z", "Datsun 260Z"),
            ("Datsun 280Z", "Datsun 280Z"),
            ("Datsun 310", "Datsun 310"),
            ("Datsun 510", "Datsun 510"),
            ("Datsun 620", "Datsun 620"),
            ("Datsun 720", "Datsun 720"),
            ("Datsun 810", "Datsun 810"),
            ("Datsun B210", "Datsun B210"),
            ("Datsun F10", "Datsun F10"),
            ("Datsun Maxima", "Datsun Maxima"),
            ("Datsun Pulsar", "Datsun Pulsar"),
            ("Datsun Skyline", "Datsun Skyline"),
            ("Datsun Sunny", "Datsun Sunny"),
        ),
    ),
    (
        "DODGE",
        (
            ("Dodge Challenger", "Dodge Challenger"),
            ("Dodge Charger", "Dodge Charger"),
            ("Dodge Grand Caravan", "Dodge Grand Caravan"),
            ("Dodge Journey", "Dodge Journey"),
            ("Dodge Neon", "Dodge Neon"),
            ("Dodge Nitro", "Dodge Nitro"),
            ("Dodge Ram", "Dodge Ram"),
            ("Dodge Viper", "Dodge Viper"),
            ("Dodge Avenger", "Dodge Avenger"),
            ("Dodge Caliber", "Dodge Caliber"),
            ("Dodge Caravan", "Dodge Caravan"),
            ("Dodge Colt", "Dodge Colt"),
            ("Dodge Dakota", "Dodge Dakota"),
            ("Dodge Dart", "Dodge Dart"),
            ("Dodge Diplomat", "Dodge Diplomat"),
            ("Dodge Intrepid", "Dodge Intrepid"),
            ("Dodge Magnum", "Dodge Magnum"),
            ("Dodge Monaco", "Dodge Monaco"),
            ("Dodge Polara", "Dodge Polara"),
            ("Dodge Raider", "Dodge Raider"),
            ("Dodge Shadow", "Dodge Shadow"),
            ("Dodge Spirit", "Dodge Spirit"),
            ("Dodge Stealth", "Dodge Stealth"),
            ("Dodge Stratus", "Dodge Stratus"),
        ),
    ),
    (
        "FERRARI",
        (
            ("Ferrari 212 Inter", "Ferrari 212 Inter"),
            ("Ferrari 225 S", "Ferrari 225 S"),
            ("Ferrari 250 GT", "Ferrari 250 GT"),
            ("Ferrari 250 Testa Rossa", "Ferrari 250 Testa Rossa"),
            ("Ferrari 275 GTB/4", "Ferrari 275 GTB/4"),
            ("Ferrari 288 GTO", "Ferrari 288 GTO"),
            ("Ferrari 308 GTB", "Ferrari 308 GTB"),
            ("Ferrari 328", "Ferrari 328"),
            ("Ferrari 330 P4", "Ferrari 330 P4"),
            ("Ferrari 348", "Ferrari 348"),
            ("Ferrari 360 Modena", "Ferrari 360 Modena"),
            ("Ferrari 365 GTB/4 Daytona", "Ferrari 365 GTB/4 Daytona"),
            ("Ferrari 365 GT4 2+2", "Ferrari 365 GT4 2+2"),
            ("Ferrari 365 GTC/4", "Ferrari 365 GTC/4"),
            ("Ferrari 365 GTS/4 Daytona Spyder", "Ferrari 365 GTS/4 Daytona Spyder"),
            ("Ferrari 456", "Ferrari 456"),
            ("Ferrari 458 Italia", "Ferrari 458 Italia"),
            ("Ferrari 488", "Ferrari 488"),
            ("Ferrari 512 BB", "Ferrari 512 BB"),
            ("Ferrari 550 Maranello", "Ferrari 550 Maranello"),
            ("Ferrari 575M Maranello", "Ferrari 575M Maranello"),
            ("Ferrari 599 GTB Fiorano", "Ferrari 599 GTB Fiorano"),
            ("Ferrari 612 Scaglietti", "Ferrari 612 Scaglietti"),
            ("Ferrari California", "Ferrari California"),
            ("Ferrari Dino 206 GT", "Ferrari Dino 206 GT"),
            ("Ferrari Enzo", "Ferrari Enzo"),
            ("Ferrari F12berlinetta", "Ferrari F12berlinetta"),
            ("Ferrari F355", "Ferrari F355"),
            ("Ferrari F40", "Ferrari F40"),
            ("Ferrari F430", "Ferrari F430"),
            ("Ferrari F50", "Ferrari F50"),
            ("Ferrari FF", "Ferrari FF"),
            ("Ferrari LaFerrari", "Ferrari LaFerrari"),
            ("Ferrari Mondial", "Ferrari Mondial"),
            ("Ferrari Portofino", "Ferrari Portofino"),
            ("Ferrari Roma", "Ferrari Roma"),
            ("Ferrari Testarossa", "Ferrari Testarossa"),
        ),
    ),
    (
        "FIAT",
        (
            ("Fiat 124 Spider", "Fiat 124 Spider"),
            ("Fiat 500", "Fiat 500"),
            ("Fiat 500 Abarth", "Fiat 500 Abarth"),
            ("Fiat 500L", "Fiat 500L"),
            ("Fiat 500X", "Fiat 500X"),
            ("Fiat 500e", "Fiat 500e"),
            ("Fiat 500C", "Fiat 500C"),
            ("Fiat 500L MPV", "Fiat 500L MPV"),
            ("Fiat Bravo", "Fiat Bravo"),
            ("Fiat Doblo", "Fiat Doblo"),
            ("Fiat Ducato", "Fiat Ducato"),
            ("Fiat Freemont", "Fiat Freemont"),
            ("Fiat Fullback", "Fiat Fullback"),
            ("Fiat Grande Punto", "Fiat Grande Punto"),
            ("Fiat Idea", "Fiat Idea"),
            ("Fiat Marea", "Fiat Marea"),
            ("Fiat Multipla", "Fiat Multipla"),
            ("Fiat Panda", "Fiat Panda"),
            ("Fiat Punto", "Fiat Punto"),
            ("Fiat Qubo", "Fiat Qubo"),
            ("Fiat Scudo", "Fiat Scudo"),
            ("Fiat Sedici", "Fiat Sedici"),
            ("Fiat Stilo", "Fiat Stilo"),
            ("Fiat Talento", "Fiat Talento"),
            ("Fiat Tipo", "Fiat Tipo"),
            ("Fiat Ulysse", "Fiat Ulysse"),
            ("Fiat Uno", "Fiat Uno"),
            ("Fiat X1/9", "Fiat X1/9"),
        ),
    ),
    (
        "FORD",
        (
            ("Ford models:", "Ford models:"),
            ("Ford Bronco", "Ford Bronco"),
            ("Ford C-Max", "Ford C-Max"),
            ("Ford Crown Victoria ", "Ford Crown Victoria "),
            ("Ford EcoSport", "Ford EcoSport"),
            ("Ford Edge", "Ford Edge"),
            ("Ford Escape", "Ford Escape"),
            ("Ford Escort ", "Ford Escort "),
            ("Ford Everest", "Ford Everest"),
            ("Ford Excursion ", "Ford Excursion "),
            ("Ford Expedition", "Ford Expedition"),
            ("Ford Explorer", "Ford Explorer"),
            ("Ford F-150", "Ford F-150"),
            ("Ford F-250", "Ford F-250"),
            ("Ford F-350", "Ford F-350"),
            ("Ford F-450", "Ford F-450"),
            ("Ford F-550", "Ford F-550"),
            ("Ford Fiesta", "Ford Fiesta"),
            ("Ford Five Hundred ", "Ford Five Hundred "),
            ("Ford Flex ", "Ford Flex "),
            ("Ford Focus ", "Ford Focus "),
            ("Ford Freestar ", "Ford Freestar "),
            ("Ford Freestyle ", "Ford Freestyle "),
            ("Ford Fusion", "Ford Fusion"),
            ("Ford Galaxy", "Ford Galaxy"),
            ("Ford GT", "Ford GT"),
            ("Ford Ka", "Ford Ka"),
            ("Ford Kuga", "Ford Kuga"),
            ("Ford Maverick ", "Ford Maverick "),
            ("Ford Mondeo", "Ford Mondeo"),
            ("Ford Mustang", "Ford Mustang"),
            ("Ford Puma", "Ford Puma"),
            ("Ford Ranger", "Ford Ranger"),
            ("Ford S-Max", "Ford S-Max"),
            ("Ford Taurus ", "Ford Taurus "),
            ("Ford Tempo ", "Ford Tempo "),
            ("Ford Thunderbird ", "Ford Thunderbird "),
            ("Ford Transit", "Ford Transit"),
            ("Ford Windstar ", "Ford Windstar "),
        ),
    ),
    (
        "FREIGHTLINER",
        (
            ("Freightliner Cascadia", "Freightliner Cascadia"),
            ("Freightliner Century Class", "Freightliner Century Class"),
            ("Freightliner Coronado", "Freightliner Coronado"),
            ("Freightliner Columbia", "Freightliner Columbia"),
            ("Freightliner M2 106", "Freightliner M2 106"),
            ("Freightliner M2 112", "Freightliner M2 112"),
            ("Freightliner 114SD", "Freightliner 114SD"),
            ("Freightliner 122SD", "Freightliner 122SD"),
            ("Freightliner Business Class M2", "Freightliner Business Class M2"),
            ("Freightliner Sprinter Van", "Freightliner Sprinter Van"),
        ),
    ),
    (
        "GMC",
        (
            ("GMC Acadia", "GMC Acadia"),
            ("GMC Canyon", "GMC Canyon"),
            ("GMC Envoy ", "GMC Envoy "),
            ("GMC Jimmy ", "GMC Jimmy "),
            ("GMC Safari ", "GMC Safari "),
            ("GMC Savana", "GMC Savana"),
            ("GMC Sierra 1500", "GMC Sierra 1500"),
            ("GMC Sierra 2500HD", "GMC Sierra 2500HD"),
            ("GMC Sierra 3500HD", "GMC Sierra 3500HD"),
            ("GMC Terrain", "GMC Terrain"),
            ("GMC Yukon", "GMC Yukon"),
            ("GMC Yukon XL", "GMC Yukon XL"),
        ),
    ),
    (
        "GENESIS",
        (
            ("Genesis G70", "Genesis G70"),
            ("Genesis G80", "Genesis G80"),
            ("Genesis G90", "Genesis G90"),
        ),
    ),
    (
        "HINO",
        (
            ("Hino 155", "Hino 155"),
            ("Hino 195", "Hino 195"),
            ("Hino 258", "Hino 258"),
            ("Hino 268", "Hino 268"),
            ("Hino 338", "Hino 338"),
            ("Hino 358", "Hino 358"),
            ("Hino 500 Series", "Hino 500 Series"),
            ("Hino 700 Series", "Hino 700 Series"),
        ),
    ),
    (
        "HONDA",
        (
            ("Honda Accord", "Honda Accord"),
            ("Honda Accord Hybrid", "Honda Accord Hybrid"),
            ("Honda Amaze", "Honda Amaze"),
            ("Honda Avancier", "Honda Avancier"),
            ("Honda Ballade", "Honda Ballade"),
            ("Honda Brio", "Honda Brio"),
            ("Honda BR-V", "Honda BR-V"),
            ("Honda City", "Honda City"),
            ("Honda Civic", "Honda Civic"),
            ("Honda Clarity", "Honda Clarity"),
            ("Honda CR-V", "Honda CR-V"),
            ("Honda CR-V Hybrid", "Honda CR-V Hybrid"),
            ("Honda CR-Z ", "Honda CR-Z "),
            ("Honda Crosstour ", "Honda Crosstour "),
            ("Honda E", "Honda E"),
            ("Honda Element ", "Honda Element "),
            ("Honda Fit", "Honda Fit"),
            ("Honda Fit/Jazz Hybrid", "Honda Fit/Jazz Hybrid"),
            ("Honda Freed", "Honda Freed"),
            ("Honda HR-V", "Honda HR-V"),
            ("Honda Insight", "Honda Insight"),
            ("Honda Integra ", "Honda Integra "),
            ("Honda Jade", "Honda Jade"),
            (
                "Honda Jazz or Fit",
                "Honda Jazz or Fit",
            ),
            ("Honda Legend", "Honda Legend"),
            ("Honda Mobilio", "Honda Mobilio"),
            ("Honda N-Box", "Honda N-Box"),
            ("Honda N-One", "Honda N-One"),
            ("Honda N-Van", "Honda N-Van"),
            ("Honda NSX", "Honda NSX"),
            ("Honda Odyssey", "Honda Odyssey"),
            ("Honda Passport", "Honda Passport"),
            ("Honda Pilot", "Honda Pilot"),
            ("Honda Prelude ", "Honda Prelude "),
            ("Honda Ridgeline", "Honda Ridgeline"),
            ("Honda S660", "Honda S660"),
            ("Honda Shuttle", "Honda Shuttle"),
            ("Honda StepWGN", "Honda StepWGN"),
            ("Honda UR-V", "Honda UR-V"),
            (
                "Honda Vezel or HR-V",
                "Honda Vezel or HR-V",
            ),
        ),
    ),
    (
        "HUMMER",
        (
            ("Hummer H1", "Hummer H1"),
            ("Hummer H2", "Hummer H2"),
            ("Hummer H3", "Hummer H3"),
            ("Hummer H3T", "Hummer H3T"),
        ),
    ),
    (
        "HYUNDAI",
        (
            ("Hyundai Accent", "Hyundai Accent"),
            ("Hyundai Accent Hatchback", "Hyundai Accent Hatchback"),
            ("Hyundai Alcazar", "Hyundai Alcazar"),
            ("Hyundai Elantra", "Hyundai Elantra"),
            ("Hyundai Elantra GT", "Hyundai Elantra GT"),
            ("Hyundai Elantra N", "Hyundai Elantra N"),
            ("Hyundai Entourage ", "Hyundai Entourage "),
            ("Hyundai Eon", "Hyundai Eon"),
            ("Hyundai Equus ", "Hyundai Equus "),
            ("Hyundai Genesis ", "Hyundai Genesis "),
            ("Hyundai Genesis Coupe ", "Hyundai Genesis Coupe "),
            ("Hyundai Getz ", "Hyundai Getz "),
            ("Hyundai Grand i10", "Hyundai Grand i10"),
            (
                "Hyundai Grandeur or Azera",
                "Hyundai Grandeur or Azera",
            ),
            ("Hyundai H-1", "Hyundai H-1"),
            ("Hyundai i10", "Hyundai i10"),
            ("Hyundai i20", "Hyundai i20"),
            ("Hyundai i30", "Hyundai i30"),
            ("Hyundai i40", "Hyundai i40"),
            ("Hyundai Ioniq", "Hyundai Ioniq"),
            ("Hyundai Kona", "Hyundai Kona"),
            ("Hyundai Kona Electric", "Hyundai Kona Electric"),
            ("Hyundai Matrix ", "Hyundai Matrix "),
            ("Hyundai Nexo", "Hyundai Nexo"),
            ("Hyundai Palisade", "Hyundai Palisade"),
            ("Hyundai Santa Cruz", "Hyundai Santa Cruz"),
            ("Hyundai Santa Fe", "Hyundai Santa Fe"),
            ("Hyundai Sonata", "Hyundai Sonata"),
            ("Hyundai Sonata Hybrid", "Hyundai Sonata Hybrid"),
            (
                "Hyundai Starex or H-1",
                "Hyundai Starex or H-1",
            ),
            ("Hyundai Terracan ", "Hyundai Terracan "),
            ("Hyundai Tucson", "Hyundai Tucson"),
            ("Hyundai Venue", "Hyundai Venue"),
            ("Hyundai Veracruz ", "Hyundai Veracruz "),
            ("Hyundai Verna", "Hyundai Verna"),
            (
                "Hyundai Xcent or  Grand i10 Sedan",
                "Hyundai Xcent or  Grand i10 Sedan",
            ),
        ),
    ),
    (
        "INFINITI",
        (
            ("Infiniti Q50", "Infiniti Q50"),
            ("Infiniti Q60", "Infiniti Q60"),
            (
                "Infiniti Q70 or M",
                "Infiniti Q70 or M",
            ),
            ("Infiniti QX30", "Infiniti QX30"),
            ("Infiniti QX50", "Infiniti QX50"),
            ("Infiniti QX55", "Infiniti QX55"),
            ("Infiniti QX60", "Infiniti QX60"),
            (
                "Infiniti QX70 or FX",
                "Infiniti QX70 or FX",
            ),
            ("Infiniti QX80", "Infiniti QX80"),
        ),
    ),
    (
        "IZUZU",
        (
            ("Isuzu Ascender ", "Isuzu Ascender "),
            (
                "Isuzu Amigo or MU",
                "Isuzu Amigo or MU",
            ),
            ("Isuzu Axiom ", "Isuzu Axiom "),
            ("Isuzu D-Max", "Isuzu D-Max"),
            ("Isuzu Hombre ", "Isuzu Hombre "),
            ("Isuzu i-Series ", "Isuzu i-Series "),
            ("Isuzu Impulse ", "Isuzu Impulse "),
            ("Isuzu Oasis ", "Isuzu Oasis "),
            (
                "Isuzu P up or KB",
                "Isuzu P up or KB",
            ),
            (
                "Isuzu Trooper or Bighorn",
                "Isuzu Trooper or Bighorn ",
            ),
            ("Isuzu VehiCROSS ", "Isuzu VehiCROSS "),
        ),
    ),
    (
        "JAGUAR",
        (
            ("Jaguar F-PACE", "Jaguar F-PACE"),
            ("Jaguar E-PACE", "Jaguar E-PACE"),
            ("Jaguar I-PACE", "Jaguar I-PACE"),
            ("Jaguar XE", "Jaguar XE"),
            ("Jaguar XF", "Jaguar XF"),
            ("Jaguar XJ ", "Jaguar XJ "),
            ("Jaguar XK ", "Jaguar XK "),
            ("Jaguar F-TYPE", "Jaguar F-TYPE"),
        ),
    ),
    (
        "JEEP",
        (
            ("Jeep models:", "Jeep models:"),
            ("Jeep Cherokee", "Jeep Cherokee"),
            ("Jeep Compass", "Jeep Compass"),
            ("Jeep Gladiator", "Jeep Gladiator"),
            ("Jeep Grand Cherokee", "Jeep Grand Cherokee"),
            ("Jeep Renegade", "Jeep Renegade"),
            ("Jeep Wrangler", "Jeep Wrangler"),
        ),
    ),
    (
        "KIA",
        (
            ("Kia models:", "Kia models:"),
            ("Kia Rio", "Kia Rio"),
            ("Kia Forte", "Kia Forte"),
            (
                "Kia Optima or K5",
                "Kia Optima or K5,",
            ),
            ("Kia Stinger", "Kia Stinger"),
            ("Kia Cadenza", "Kia Cadenza"),
            ("Kia K900", "Kia K900"),
            ("Kia Soul", "Kia Soul"),
            (
                "Kia Niro",
                "Kia Niro",
            ),
            ("Kia Seltos", "Kia Seltos"),
            ("Kia Sportage", "Kia Sportage"),
            ("Kia Sorento", "Kia Sorento"),
            ("Kia Telluride", "Kia Telluride"),
        ),
    ),
    (
        "LAND ROVER",
        (
            ("Land Rover Defender", "Land Rover Defender"),
            ("Land Rover Discovery", "Land Rover Discovery"),
            ("Land Rover Discovery Sport", "Land Rover Discovery Sport"),
            ("Land Rover Range Rover", "Land Rover Range Rover"),
            ("Land Rover Range Rover Sport", "Land Rover Range Rover Sport"),
            ("Land Rover Range Rover Velar", "Land Rover Range Rover Velar"),
            ("Land Rover Range Rover Evoque", "Land Rover Range Rover Evoque"),
        ),
    ),
    (
        "LAMBORGHINI",
        (
            ("Lamborghini Huracán", "Lamborghini Huracán"),
            ("Lamborghini Aventador", "Lamborghini Aventador"),
            ("Lamborghini Urus", "Lamborghini Urus"),
            ("Lamborghini Diablo", "Lamborghini Diablo"),
            ("Lamborghini Murciélago", "Lamborghini Murciélago"),
            ("Lamborghini Countach", "Lamborghini Countach"),
            ("Lamborghini Gallardo", "Lamborghini Gallardo"),
            ("Lamborghini Veneno", "Lamborghini Veneno"),
            ("Lamborghini Sesto Elemento", "Lamborghini Sesto Elemento"),
            ("Lamborghini Reventón", "Lamborghini Reventón"),
            ("Lamborghini Miura", "Lamborghini Miura"),
            ("Lamborghini Espada", "Lamborghini Espada"),
            ("Lamborghini Jarama", "Lamborghini Jarama"),
            ("Lamborghini LM002", "Lamborghini LM002"),
        ),
    ),
    (
        "LEXUS",
        (
            ("Lexus ES", "Lexus ES"),
            ("Lexus IS", "Lexus IS"),
            ("Lexus LS", "Lexus LS"),
            ("Lexus LC", "Lexus LC"),
            ("Lexus RC", "Lexus RC"),
            ("Lexus UX", "Lexus UX"),
            ("Lexus NX", "Lexus NX"),
            ("Lexus RX", "Lexus RX"),
            ("Lexus GX", "Lexus GX"),
            ("Lexus LX", "Lexus LX"),
            ("Lexus LFA ", "Lexus LFA "),
        ),
    ),
    (
        "LINCOLN",
        (
            ("Lincoln Aviator", "Lincoln Aviator"),
            ("Lincoln Continental ", "Lincoln Continental "),
            ("Lincoln Corsair", "Lincoln Corsair"),
            ("Lincoln MKC ", "Lincoln MKC "),
            ("Lincoln MKS ", "Lincoln MKS "),
            ("Lincoln MKT ", "Lincoln MKT "),
            (
                "Lincoln MKX or Nautilus",
                "Lincoln MKX or Nautilus",
            ),
            ("Lincoln Navigator", "Lincoln Navigator"),
            ("Lincoln Town Car ", "Lincoln Town Car "),
            ("Lincoln Zephyr ", "Lincoln Zephyr "),
        ),
    ),
    (
        "MACK",
        (
            ("Mack Anthem", "Mack Anthem"),
            ("Mack Granite", "Mack Granite"),
            ("Mack Pinnacle", "Mack Pinnacle"),
            ("Mack TerraPro", "Mack TerraPro"),
            ("Mack LR", "Mack LR"),
            ("Mack CH", "Mack CH"),
            ("Mack Vision", "Mack Vision"),
            ("Mack Metro Liner", "Mack Metro Liner"),
            ("Mack Super-Liner", "Mack Super-Liner"),
            ("Mack Titan", "Mack Titan"),
            ("Mack R Series ", "Mack R Series "),
            ("Mack DM Series ", "Mack DM Series "),
        ),
    ),
    (
        "MASERATI",
        (
            ("Maserati models:", "Maserati models:"),
            ("Maserati Ghibli", "Maserati Ghibli"),
            ("Maserati Levante", "Maserati Levante"),
            ("Maserati Quattroporte", "Maserati Quattroporte"),
            ("Maserati GranTurismo ", "Maserati GranTurismo "),
            ("Maserati GranCabrio ", "Maserati GranCabrio "),
        ),
    ),
    (
        "MCLAREN",
        (
            ("McLaren 540C", "McLaren 540C"),
            ("McLaren 570S", "McLaren 570S"),
            ("McLaren 570GT", "McLaren 570GT"),
            ("McLaren 600LT", "McLaren 600LT"),
            ("McLaren 620R", "McLaren 620R"),
            ("McLaren 720S", "McLaren 720S"),
            ("McLaren GT", "McLaren GT"),
            ("McLaren P1 ", "McLaren P1 "),
            ("McLaren Senna ", "McLaren Senna "),
        ),
    ),
    (
        "MERCEDES BENZ",
        (
            ("Mercedes Benz A-Class Sedan", "Mercedes Benz A-Class Sedan"),
            ("Mercedes Benz A-Class Hatchback", "Mercedes Benz A-Class Hatchback"),
            ("Mercedes Benz A-Class L Sedan", "Mercedes Benz A-Class L Sedan"),
            ("Mercedes Benz A-Class L Saloon", "Mercedes Benz A-Class L Saloon"),
            ("Mercedes Benz B-Class Hatchback", "Mercedes Benz B-Class Hatchback"),
            ("Mercedes Benz C-Class Sedan", "Mercedes Benz C-Class Sedan"),
            ("Mercedes Benz C-Class Coupe", "CMercedes Benz -Class Coupe"),
            ("Mercedes Benz C-Class Cabriolet", "Mercedes Benz C-Class Cabriolet"),
            ("Mercedes Benz C-Class Wagon", "Mercedes Benz C-Class Wagon"),
            ("Mercedes Benz CLA-Class Coupe", "Mercedes Benz CLA-Class Coupe"),
            (
                "Mercedes Benz CLA-Class Shooting Brake",
                "Mercedes Benz CLA-Class Shooting Brake",
            ),
            ("Mercedes Benz CLS-Class Coupe", "CMercedes Benz LS-Class Coupe"),
            (
                "Mercedes Benz CLS-Class Shooting Brake",
                "Mercedes Benz CLS-Class Shooting Brake",
            ),
            ("Mercedes Benz E-Class Sedan", "Mercedes Benz E-Class Sedan"),
            ("Mercedes Benz E-Class Coupe", "Mercedes Benz E-Class Coupe"),
            ("Mercedes Benz E-Class Cabriolet", "Mercedes Benz E-Class Cabriolet"),
            ("Mercedes Benz E-Class Wagon", "Mercedes Benz E-Class Wagon"),
            ("Mercedes Benz E-Class All-Terrain", "Mercedes Benz E-Class All-Terrain"),
            ("Mercedes Benz G-Class SUV", "Mercedes Benz G-Class SUV"),
            ("Mercedes Benz GLA-Class SUV", "Mercedes Benz GLA-Class SUV"),
            ("Mercedes Benz GLB-Class SUV", "Mercedes Benz GLB-Class SUV"),
            ("Mercedes Benz GLC-Class SUV", "Mercedes Benz GLC-Class SUV"),
            ("Mercedes Benz GLC-Class Coupe", "Mercedes Benz GLC-Class Coupe"),
            ("Mercedes Benz GLE-Class SUV", "Mercedes Benz GLE-Class SUV"),
            ("Mercedes Benz GLE-Class Coupe", "Mercedes Benz GLE-Class Coupe"),
            ("Mercedes Benz GLS-Class SUV", "Mercedes Benz GLS-Class SUV"),
            ("Mercedes Benz S-Class Sedan", "Mercedes Benz S-Class Sedan"),
            ("Mercedes Benz S-Class Coupe", "Mercedes Benz S-Class Coupe"),
            ("Mercedes Benz S-Class Cabriolet", "Mercedes Benz S-Class Cabriolet"),
            ("Mercedes Benz SL-Class Roadster", "Mercedes Benz SL-Class Roadster"),
            ("Mercedes Benz SLC-Class Roadster", "Mercedes Benz SLC-Class Roadster"),
            ("Mercedes Benz AMG GT Coupe", "Mercedes Benz AMG GT Coupe"),
            ("Mercedes Benz AMG GT Roadster", "Mercedes Benz AMG GT Roadster"),
            ("Mercedes Benz AMG GT 4-Door Coupe", "Mercedes Benz AMG GT 4-Door Coupe"),
            ("Mercedes Benz Maybach S-Class", "Mercedes Benz Maybach S-Class"),
        ),
    ),
    (
        "MAZDA",
        (
            (
                "Mazda2 or Demio",
                "Mazda2 or Demio",
            ),
            (
                "Mazda3 or Mazda",
                "Mazda3 or Mazda",
            ),
            (
                "Mazda5 or  Premacy",
                "Mazda5 or  Premacy",
            ),
            (
                "Mazda6 or Atenza",
                "Mazda6 or Atenza",
            ),
            (
                "Mazda MX-5 or Miata or Eunos Roadster",
                "Mazda MX-5 or Miata or Eunos Roadster",
            ),
            ("Mazda CX-3", "Mazda CX-3"),
            ("Mazda CX-30", "Mazda CX-30"),
            ("Mazda CX-5", "Mazda CX-5"),
            ("Mazda CX-7 ", "Mazda CX-7 "),
            ("Mazda CX-9", "Mazda CX-9"),
            ("Mazda RX-8 ", "Mazda RX-8 "),
            ("Mazda B-Series ", "Mazda B-Series "),
            ("Mazda MPV ", "Mazda MPV "),
            ("Mazda Tribute ", "Mazda Tribute "),
        ),
    ),
    (
        "MECURY",
        (
            ("MECURY Eight ", "MECURY Eight "),
            ("MECURY Monterey  ", "MECURY Monterey  "),
            ("MECURY Comet  ", "MECURY Comet  "),
            ("MECURY Cougar  ", "MECURY Cougar  "),
            ("MECURY Marquis ", "MECURY Marquis "),
            ("MECURY Montego ", "MECURY Montego "),
            ("MECURY Cyclone ", "MECURY Cyclone "),
            ("MECURY Capri ", "MECURY Capri "),
            ("MECURY Bobcat ", "MECURY Bobcat "),
            ("MECURY Zephyr ", "MECURY Zephyr "),
            ("MECURY Lynx ", "MECURY Lynx "),
            ("MECURY Topaz ", "MECURY Topaz "),
            ("MECURY Grand Marquis ", "MECURY Grand Marquis "),
            ("MECURY Sable ", "MECURY Sable "),
            ("MECURY Tracer ", "MECURY Tracer "),
            ("MECURY Villager  ", "MECURY Villager  "),
            ("MECURY Mountaineer  ", "MECURY Mountaineer  "),
            ("MECURY Marauder  ", "MECURY Marauder  "),
            ("MECURY Milan  ", "MECURY Milan  "),
            ("MECURY Mariner  ", "MECURY Mariner   "),
        ),
    ),
    (
        "MINI",
        (
            (
                "Mini Hatch or Cooper or One",
                "Mini Hatch or Cooper or One",
            ),
            ("Mini Convertible", "Mini Convertible"),
            ("Mini Clubman", "Mini Clubman"),
            ("Mini Countryman", "Mini Countryman"),
            ("Mini Coupe ", "Mini Coupe "),
            ("Mini Roadster ", "Mini Roadster "),
            ("Mini Paceman ", "Mini Paceman "),
        ),
    ),
    (
        "MITSUBISHI", 
        (
            (
                "Mitsubishi Mirage or Space Star",
                "Mitsubishi Mirage or Space Star",
            ),
            (
                "Mitsubishi Attrage or Mirage G4",
                "Mitsubishi Attrage or Mirage G4",
            ),
            ("Mitsubishi Lancer", "Mitsubishi Lancer"),
            ("Mitsubishi Galant ", "Mitsubishi Galant "),
            ("Mitsubishi Eclipse Cross", "Mitsubishi Eclipse Cross"),
            ("Mitsubishi Outlander", "Mitsubishi Outlander"),
            (
                "Mitsubishi ASX or RVR or Outlander Sport",
                "Mitsubishi ASX or RVR or Outlander Sport",
            ),
            (
                "Mitsubishi Pajero or Montero or Shogun",
                "Mitsubishi Pajero or Montero or Shogun",
            ),
            (
                "Mitsubishi Delica or L300 or Starwagon",
                "Mitsubishi Delica or L300 or Starwagon",
            ),
            (
                "Mitsubishi Triton or L200",
                "Mitsubishi Triton or L200",
            ),
            (
                "Mitsubishi Fuso Canter",
                "Mitsubishi Fuso Canter",
            ),
        ),
    ),
    (
        "NISSAN",
        (
            (
                "Nissan Versa or Tiida or Latio",
                "Nissan Versa or Tiida or Latio",
            ),
            (
                "Nissan Sentra or Sylphy",
                "Nissan Sentra or Sylphy",
            ),
            ("Nissan Altima", "Nissan Altima"),
            ("Nissan Maxima", "Nissan Maxima"),
            ("Nissan Leaf ", "Nissan Leaf "),
            ("Nissan Juke ", "Nissan Juke "),
            ("Nissan Kicks", "Nissan Kicks"),
            (
                "Nissan Rogue or X-Trail",
                "Nissan Rogue or X-Trail",
            ),
            ("Nissan Murano", "Nissan Murano"),
            ("Nissan Pathfinder", "Nissan Pathfinder"),
            ("Nissan Armada", "Nissan Armada"),
            (
                "Nissan Frontier or Navara",
                "Nissan Frontier or Navara",
            ),
            ("Nissan Titan", "Nissan Titan"),
            ("Nissan GT-R", "Nissan GT-R"),
            ("Nissan 370Z", "Nissan 370Z"),
        ),
    ),
    (
        "OLDSMOBILE",
        (
            ("Oldsmobile Curved Dash ", "Oldsmobile Curved Dash "),
            ("Oldsmobile Limited ", "Oldsmobile Limited "),
            ("Oldsmobile Model 44 ", "Oldsmobile Model 44 "),
            ("Oldsmobile Model 60 ", "Oldsmobile Model 60 "),
            ("Oldsmobile Model 66 ", "Oldsmobile Model 66 "),
            ("Oldsmobile Model 68 ", "Oldsmobile Model 68 "),
            ("Oldsmobile Model 90 ", "Oldsmobile Model 90 "),
            ("Oldsmobile Model F ", "Oldsmobile Model F "),
            ("Oldsmobile Series 60 ", "Oldsmobile Series 60 "),
            ("Oldsmobile Series 70 ", "Oldsmobile Series 70 "),
            ("Oldsmobile Series 80 ", "Oldsmobile Series 80 "),
            ("Oldsmobile Series 90 ", "Oldsmobile Series 90 "),
            ("Oldsmobile Series 88 ", "Oldsmobile Series 88 "),
            ("Oldsmobile Starfire ", "Oldsmobile Starfire "),
            ("Oldsmobile 442 ", "Oldsmobile 442 "),
            ("Oldsmobile Toronado ", "Oldsmobile Toronado "),
            ("Oldsmobile Cutlass ", "Oldsmobile Cutlass "),
            ("Oldsmobile Omega ", "Oldsmobile Omega "),
            ("Oldsmobile Achieva ", "Oldsmobile Achieva "),
            ("Oldsmobile Alero ", "Oldsmobile Alero "),
            ("Oldsmobile Aurora ", "Oldsmobile Aurora "),
            ("Oldsmobile Bravada ", "Oldsmobile Bravada "),
            ("Oldsmobile Silhouette ", "Oldsmobile Silhouette "),
        ),
    ),
    (
        "PLYMOUTH",
        (
            ("Plymouth Acclaim", "Plymouth Acclaim"),
            ("Plymouth Arrow Pickup", "Plymouth Arrow Pickup"),
            ("Plymouth Arrow Truck", "Plymouth Arrow Truck"),
            ("Plymouth Barracuda", "Plymouth Barracuda"),
            ("Plymouth Belvedere", "Plymouth Belvedere"),
            ("Plymouth Breeze", "Plymouth Breeze"),
            ("Plymouth Cambridge", "Plymouth Cambridge"),
            ("Plymouth Caravelle", "Plymouth Caravelle"),
            ("Plymouth Champ", "Plymouth Champ"),
            ("Plymouth Colt", "Plymouth Colt"),
            ("Plymouth Conquest", "Plymouth Conquest"),
            ("Plymouth Cranbrook", "Plymouth Cranbrook"),
            ("Plymouth Cricket", "Plymouth Cricket"),
            ("Plymouth Duster", "Plymouth Duster"),
            ("Plymouth Fury", "Plymouth Fury"),
            ("Plymouth Gran Fury", "Plymouth Gran Fury"),
            ("Plymouth Grand Voyager", "Plymouth Grand Voyager"),
            ("Plymouth Horizon", "Plymouth Horizon"),
            ("Plymouth Laser", "Plymouth Laser"),
            ("Plymouth Neon", "Plymouth Neon"),
            ("Plymouth Plaza", "Plymouth Plaza"),
            ("Plymouth Prowler", "Plymouth Prowler"),
            ("Plymouth Reliant", "Plymouth Reliant"),
            ("Plymouth Road Runner", "Plymouth Road Runner"),
            ("Plymouth Sapporo", "Plymouth Sapporo"),
            ("Plymouth Satellite", "Plymouth Satellite"),
            ("Plymouth Savoy", "Plymouth Savoy"),
            ("Plymouth Scamp", "Plymouth Scamp"),
            ("Plymouth Sundance", "Plymouth Sundance"),
            ("Plymouth Superbird", "Plymouth Superbird"),
            ("Plymouth TC3", "Plymouth TC3"),
            ("Plymouth Trailduster", "Plymouth Trailduster"),
            ("Plymouth Turismo", "Plymouth Turismo"),
            ("Plymouth Valiant", "Plymouth Valiant"),
            ("Plymouth VIP", "Plymouth VIP"),
            ("Plymouth Voyager", "Plymouth Voyager"),
        ),
    ),
    (
        "POLARIS",
        (
            ("Polaris Sportsman", "Polaris Sportsman"),
            ("Polaris Scrambler", "Polaris Scrambler"),
            ("Polaris Outlaw", "Polaris Outlaw"),
            ("Polaris Trail Boss", "Polaris Trail Boss"),
            ("Polaris Phoenix", "Polaris Phoenix"),
            ("Polaris Hawkeye", "Polaris Hawkeye"),
            ("Polaris Magnum", "Polaris Magnum"),
            ("Polaris Xplorer", "Polaris Xplorer"),
            ("Polaris Trail Blazer", "Polaris Trail Blazer"),
            ("Polaris Big Boss", "Polaris Big Boss"),
            ("Polaris Worker", "Polaris Worker"),
            ("Side-by-sides:", "Side-by-sides:"),
            ("Polaris RZR", "Polaris RZR"),
            ("Polaris Ranger", "Polaris Ranger"),
            ("Polaris General", "Polaris General"),
            ("Polaris ACE", "Polaris ACE"),
            ("Snowmobiles:", "Snowmobiles:"),
            ("Polaris INDY", "Polaris INDY"),
            ("Polaris Switchback", "Polaris Switchback"),
            ("Polaris RMK", "Polaris RMK"),
            ("Polaris Titan", "Polaris Titan"),
            ("Polaris Voyageur", "Polaris Voyageur"),
            ("Motorcycles:", "Motorcycles:"),
            ("Polaris Slingshot", "Polaris Slingshot"),
            ("Polaris Victory ", "Polaris Victory "),
        ),
    ),
    (
        "PONTIAC",
        (
            ("Pontiac 2+2", "Pontiac 2+2"),
            ("Pontiac Aztek", "Pontiac Aztek"),
            ("Pontiac Bonneville", "Pontiac Bonneville"),
            ("Pontiac Catalina", "Pontiac Catalina"),
            ("Pontiac Chieftain", "Pontiac Chieftain"),
            ("Pontiac Custom S", "Pontiac Custom S"),
            ("Pontiac Fiero", "Pontiac Fiero"),
            ("Pontiac Firebird", "Pontiac Firebird"),
            ("Pontiac G3", "Pontiac G3"),
            ("Pontiac G4", "Pontiac G4"),
            ("Pontiac G5", "Pontiac G5"),
            ("Pontiac G6", "Pontiac G6"),
            ("Pontiac G8", "Pontiac G8"),
            ("Pontiac Grand Am", "Pontiac Grand Am"),
            ("Pontiac Grand Prix", "Pontiac Grand Prix"),
            ("Pontiac GTO", "Pontiac GTO"),
            ("Pontiac LeMans", "Pontiac LeMans"),
            ("Pontiac Montana", "Pontiac Montana"),
            ("Pontiac Parisienne", "Pontiac Parisienne"),
            ("Pontiac Phoenix", "Pontiac Phoenix"),
            ("Pontiac Pursuit", "Pontiac Pursuit"),
            ("Pontiac Solstice", "Pontiac Solstice"),
            ("Pontiac Star Chief", "Pontiac Star Chief"),
            ("Pontiac Streamliner", "Pontiac Streamliner"),
            ("Pontiac Sunbird", "Pontiac Sunbird"),
            ("Pontiac Sunfire", "Pontiac Sunfire"),
            ("Pontiac Super Chief", "Pontiac Super Chief"),
            ("Pontiac Tempest", "Pontiac Tempest"),
            ("Pontiac Torrent", "Pontiac Torrent"),
            ("Pontiac Trans Am", "Pontiac Trans Am"),
            ("Pontiac Ventura", "Pontiac Ventura"),
            ("Pontiac Vibe", "Pontiac Vibe"),
        ),
    ),
    (
        "RAM",
        (
            ("Ram 1500", "Ram 1500"),
            ("Ram 2500", "Ram 2500"),
            ("Ram 3500", "Ram 3500"),
            ("Ram 4500", "Ram 4500"),
            ("Ram 5500", "Ram 5500"),
            ("Ram C/V Tradesman", "Ram C/V Tradesman"),
            ("Ram Dakota ", "Ram Dakota "),
            ("Ram ProMaster", "Ram ProMaster"),
            ("Ram ProMaster City", "Ram ProMaster City"),
        ),
    ),
    (
        "ROLLS ROYCE",     (       ("Rolls-Royce Camargue", "Rolls-Royce Camargue"),
            ("Rolls-Royce Corniche", "Rolls-Royce Corniche"),
            ("Rolls-Royce Corniche II", "Rolls-Royce Corniche II"),
            ("Rolls-Royce Corniche III", "Rolls-Royce Corniche III"),
            ("Rolls-Royce Corniche IV", "Rolls-Royce Corniche IV"),
            ("Rolls-Royce Corniche V", "Rolls-Royce Corniche V"),
            ("Rolls-Royce Dawn", "Rolls-Royce Dawn"),
            ("Rolls-Royce Ghost", "Rolls-Royce Ghost"),
            ("Rolls-Royce Ghost II", "Rolls-Royce Ghost II"),
            ("Rolls-Royce Ghost III", "Rolls-Royce Ghost III"),
            ("Rolls-Royce Phantom", "Rolls-Royce Phantom"),
            ("Rolls-Royce Phantom II", "Rolls-Royce Phantom II"),
            ("Rolls-Royce Phantom III", "Rolls-Royce Phantom III"),
            ("Rolls-Royce Phantom IV", "Rolls-Royce Phantom IV"),
            ("Rolls-Royce Phantom V", "Rolls-Royce Phantom V"),
            ("Rolls-Royce Phantom VI", "Rolls-Royce Phantom VI"),
            ("Rolls-Royce Phantom VII", "Rolls-Royce Phantom VII"),
            ("Rolls-Royce Phantom VIII", "Rolls-Royce Phantom VIII"),
            ("Rolls-Royce Silver Cloud", "Rolls-Royce Silver Cloud"),
            ("Rolls-Royce Silver Dawn", "Rolls-Royce Silver Dawn"),
            ("Rolls-Royce Silver Ghost", "Rolls-Royce Silver Ghost"),
            ("Rolls-Royce Silver Shadow", "Rolls-Royce Silver Shadow"),
            ("Rolls-Royce Silver Spirit", "Rolls-Royce Silver Spirit"),
            ("Rolls-Royce Silver Spur", "Rolls-Royce Silver Spur"),
            ("Rolls-Royce Silver Wraith", "Rolls-Royce Silver Wraith"),
            ("Rolls-Royce Sweptail", "Rolls-Royce Sweptail"),
            ("Rolls-Royce Tourer", "Rolls-Royce Tourer"),
            ("Rolls-Royce Wraith", "Rolls-Royce Wraith"),
        )),
    
    (
        "SAAB",
        (
            ("Saab 92 ", "Saab 92 "),
            ("Saab 93 ", "Saab 93 "),
            ("Saab 95 ", "Saab 95 "),
            ("Saab 96 ", "Saab 96 "),
            ("Saab 99 ", "Saab 99 "),
            ("Saab Sonett ", "Saab Sonett "),
            ("Saab 900 ", "Saab 900 "),
            ("Saab 9000 ", "Saab 9000 "),
            ("Saab 9-2X ", "Saab 9-2X "),
            ("Saab 9-3 ", "Saab 9-3 "),
            ("Saab 9-4X ", "Saab 9-4X "),
            ("Saab 9-5 ", "Saab 9-5 "),
        ),
    ),
    (
        "SATURN",
        (
            ("Saturn S-Series", "Saturn S-Series"),
            ("Saturn L-Series", "Saturn L-Series"),
            ("Saturn Vue", "Saturn Vue"),
            ("Saturn Ion", "Saturn Ion"),
            ("Saturn Sky", "Saturn Sky"),
            ("Saturn Outlook", "Saturn Outlook"),
            ("Saturn Aura", "Saturn Aura"),
            ("Saturn Astra", "Saturn Astra"),
        ),
    ),
    (
        "SCION",
        (
            ("Scion xA ", "Scion xA "),
            ("Scion xB ", "Scion xB "),
            ("Scion tC ", "Scion tC "),
            ("Scion xD ", "Scion xD "),
            ("Scion iQ ", "Scion iQ "),
            ("Scion FR-S ", "Scion FR-S "),
            ("Scion iM ", "Scion iM "),
            ("Scion iA ", "Scion iA "),
        ),
    ),
    (
        "SMART",
        (
            ("Smart Fortwo ", "Smart Fortwo "),
            (
                "Smart Forfour",
                "Smart Forfour",
            ),
            ("Smart Roadster", "Smart Roadster"),
            ("Smart Crossblade ", "Smart Crossblade "),
            ("Smart City-Coupe ", "Smart City-Coupe "),
            ("Smart City-Cabriolet ", "Smart City-Cabriolet "),
            (
                "Smart Fortwo Cabriolet ",
                "Smart Fortwo Cabriolet ",
            ),
            (
                "Smart Fortwo Electric Drive ",
                "Smart Fortwo Electric Drive ",
            ),
            (
                "Smart Fortwo Brabus ",
                "Smart Fortwo Brabus ",
            ),
        ),
    ),
    (
        "SUBARU",
        (
            ("Subaru 1500 ", "Subaru 1500 "),
            ("Subaru 360 ", "Subaru 360 "),
            ("Subaru Sambar ", "Subaru Sambar "),
            ("Subaru R-2 ", "Subaru R-2 "),
            ("Subaru Leone ", "Subaru Leone "),
            ("Subaru BRAT ", "Subaru BRAT "),
            ("Subaru XT ", "Subaru XT "),
            ("Subaru Legacy ", "Subaru Legacy "),
            ("Subaru Impreza ", "Subaru Impreza "),
            ("Subaru Alcyone SVX  ", "Subaru Alcyone SVX "),
            ("Subaru Forester", "Subaru Forester "),
            ("Subaru Outback ", "Subaru Outback "),
            ("Subaru Baja ", "Subaru Baja "),
            ("Subaru Tribeca ", "Subaru Tribeca "),
            ("Subaru WRX ", "Subaru WRX "),
            ("Subaru XV Crosstrek ", "Subaru XV Crosstrek "),
            ("Subaru Ascent ", "Subaru Ascent "),
            ("Subaru BRZ ", "Subaru BRZ "),
            ("Subaru Crosstrek ", "Subaru Crosstrek "),
            ("Subaru Levorg ", "Subaru Levorg "),
        ),
    ),
    (
        "SUZUKI",
        (
            ("Suzuki Aerio", "Suzuki  Aerio"),
            ("Suzuki Alto", "Suzuki  Alto"),
            ("Suzuki Baleno", "Suzuki  Baleno"),
            ("Suzuki Cappuccino", "Suzuki  Cappuccino"),
            ("Suzuki Carry", "Suzuki  Carry"),
            ("Suzuki Celerio", "Suzuki  Celerio"),
            ("Suzuki Cultus", "Suzuki  Cultus"),
            ("Suzuki Equator", "Suzuki  Equator"),
            ("Suzuki Escudo", "Suzuki  Escudo"),
            ("Suzuki Esteem", "Suzuki  Esteem"),
            ("Suzuki Every", "Suzuki  Every"),
            ("Suzuki Forenza", "Suzuki  Forenza"),
            ("Suzuki Fronte", "Suzuki  Fronte"),
            ("Suzuki Grand Vitara", "Suzuki Grand Vitara"),
            ("Suzuki Ignis", "Suzuki  Ignis"),
            ("Suzuki Jimny", "Suzuki  Jimny"),
            ("Suzuki Kizashi", "Suzuki  Kizashi"),
            ("Suzuki Lapin", "Suzuki  Lapin"),
            ("Suzuki LJ", "Suzuki  LJ"),
            ("Suzuki MR Wagon", "Suzuki MR Wagon"),
            ("Suzuki Reno", "Suzuki  Reno"),
            ("Suzuki Samurai", "Suzuki  Samurai"),
            ("Suzuki Sidekick", "Suzuki  Sidekick"),
            ("Suzuki Solio", "Suzuki  Solio"),
            ("Suzuki Splash", "Suzuki  Splash"),
            ("Suzuki Swift", "Suzuki  Swift"),
            ("Suzuki SX4", "Suzuki  SX4"),
            ("Suzuki Verona", "Suzuki  Verona"),
            ("Suzuki Vitara", "Suzuki  Vitara"),
            ("Suzuki Wagon R+", "Suzuki Wagon R+"),
        ),
    ),
    (
        "TESLA",
        (
            ("Tesla Model S", "Tesla Model S"),
            ("Tesla Model X", "Tesla Model X"),
            ("Tesla Model 3", "Tesla Model 3"),
            ("Tesla Model Y", "Tesla Model Y"),
            ("Tesla Roadster", "Tesla Roadster"),
        ),
    ),
    (
        "TOYOTA",
        (
            ("Toyota 86", "Toyota 86"),
            ("Toyota 4Runner", "Toyota 4Runner"),
            ("Toyota Avalon", "Toyota Avalon"),
            ("Toyota Avalon Hybrid", "Toyota Avalon Hybrid"),
            ("Toyota C-HR", "Toyota C-HR"),
            ("Toyota Camry", "Toyota Camry"),
            ("Toyota Camry Hybrid", "Toyota Camry Hybrid"),
            ("Toyota Corolla", "Toyota Corolla"),
            ("Toyota Corolla Hatchback", "Toyota Corolla Hatchback"),
            ("Toyota Corolla Hybrid", "Toyota Corolla Hybrid"),
            ("Toyota GR Supra", "Toyota GR Supra"),
            ("Toyota Highlander", "Toyota Highlander"),
            ("Toyota Highlander Hybrid", "Toyota Highlander Hybrid"),
            ("Toyota Land Cruiser", "Toyota Land Cruiser"),
            ("Toyota Mirai", "Toyota Mirai"),
            ("Toyota Prius", "Toyota Prius"),
            ("Toyota Prius Prime", "Toyota Prius Prime"),
            ("Toyota RAV4", "Toyota RAV4"),
            ("Toyota RAV4 Hybrid", "Toyota RAV4 Hybrid"),
            ("Toyota Sequoia", "Toyota Sequoia"),
            ("Toyota Sienna", "Toyota Sienna"),
            ("Toyota Tacoma", "Toyota Tacoma"),
            ("Toyota Tundra", "Toyota Tundra"),
            ("Toyota Venza", "Toyota Venza"),
            ("Toyota Yaris", "Toyota Yaris"),
            ("Toyota Yaris Hatchback", "Toyota Yaris Hatchback"),
        ),
    ),
    (
        "VOLKSWAGEN",
        (
            ("Volkswagen Amarok", "Volkswagen Amarok"),
            ("Volkswagen Arteon", "Volkswagen Arteon"),
            ("Volkswagen Atlas", "Volkswagen Atlas"),
            ("Volkswagen Beetle", "Volkswagen Beetle"),
            ("Volkswagen Bora", "Volkswagen Bora"),
            ("Volkswagen Caddy", "Volkswagen Caddy"),
            ("Volkswagen California", "Volkswagen California"),
            ("Volkswagen Caravelle", "Volkswagen Caravelle"),
            ("Volkswagen CC", "Volkswagen CC"),
            ("Volkswagen Corrado", "Corrado"),
            ("Volkswagen Crafter", "Crafter"),
            ("Volkswagen CrossFox", "CrossFox"),
            ("Volkswagen e-Golf", "e-Golf"),
            ("Volkswagen Eos", "Volkswagen Eos"),
            ("Volkswagen Fox", "Volkswagen Fox"),
            ("Volkswagen Golf", "Volkswagen Golf"),
            ("Volkswagen Golf Alltrack", "Volkswagen Golf Alltrack"),
            ("Volkswagen Golf GTI", "Volkswagen Golf GTI"),
            ("Volkswagen Golf R", "GVolkswagen olf R"),
            ("Volkswagen Golf SportWagen", "Volkswagen Golf SportWagen"),
            ("Volkswagen ID.3", "Volkswagen ID.3"),
            ("Volkswagen ID.4", "Volkswagen ID.4"),
            ("Volkswagen Jetta", "Volkswagen Jetta"),
            ("Volkswagen K70", "Volkswagen K70"),
            ("Volkswagen Karmann Ghia", "Volkswagen Karmann Ghia"),
            ("Volkswagen Lupo", "Volkswagen Lupo"),
            ("Volkswagen Multivan", "Volkswagen Multivan"),
            ("Volkswagen New Beetle", "Volkswagen New Beetle"),
            ("Volkswagen Passat", "Volkswagen Passat"),
            ("Volkswagen Phaeton", "Volkswagen Phaeton"),
            ("Volkswagen Polo", "Volkswagen Polo"),
            ("Volkswagen Rabbit", "Volkswagen Rabbit"),
            ("Volkswagen Santana", "Volkswagen Santana"),
            ("Volkswagen Scirocco", "Volkswagen Scirocco"),
            ("Volkswagen Sharan", "Volkswagen Sharan"),
            ("Volkswagen T-Cross", "Volkswagen T-Cross"),
            ("Volkswagen T-Roc", "Volkswagen T-Roc"),
            ("Volkswagen Tiguan", "Volkswagen Tiguan"),
            ("Volkswagen Touareg", "Volkswagen Touareg"),
            ("Volkswagen Touran", "Volkswagen Touran"),
            ("Volkswagen Transporter", "Volkswagen Transporter"),
            ("Volkswagen up!", "Volkswagen up!"),
        ),
    ),
    (
        "VOLVO",
        (
            ("Volvo 120 Series", "Volvo 120 Series"),
            ("Volvo 140 Series", "Volvo 140 Series"),
            ("Volvo 164", "Volvo 164"),
            ("Volvo 1800", "Volvo 1800"),
            ("Volvo 200 Series", "Volvo 200 Series"),
            ("Volvo 300 Series", "Volvo 300 Series"),
            ("Volvo 400 Series", "Volvo 400 Series"),
            ("Volvo 480", "Volvo 480"),
            ("Volvo 66", "Volvo 66"),
            ("Volvo 700 Series", "Volvo 700 Series"),
            ("Volvo 800 Series", "Volvo 800 Series"),
            ("Volvo 850", "Volvo 850"),
            ("Volvo 900 Series", "Volvo 900 Series"),
            ("Volvo C30", "Volvo C30"),
            ("Volvo C70", "Volvo C70"),
            ("Volvo Cross Country", "Volvo Cross Country"),
            ("Volvo P1800", "Volvo P1800"),
            ("Volvo S40", "Volvo S40"),
            ("Volvo S60", "Volvo S60"),
            ("Volvo S70", "Volvo S70"),
            ("Volvo S80", "Volvo S80"),
            ("Volvo S90", "Volvo S90"),
            ("Volvo V40", "Volvo V40"),
            ("Volvo V50", "Volvo V50"),
            ("Volvo V60", "Volvo V60"),
            ("Volvo V70", "Volvo V70"),
            ("Volvo V90", "Volvo V90"),
            ("Volvo XC40", "Volvo XC40"),
            ("Volvo XC60", "Volvo XC60"),
            ("Volvo XC70", "Volvo XC70"),
            ("Volvo XC90", "Volvo XC90"),
        ),
    ),
    (
        "WINNEBAGO",
        (
            ("Winnebago Adventurer", "Winnebago Adventurer"),
            ("Winnebago Aspect", "Winnebago Aspect"),
            ("Winnebago Brave", "Winnebago Brave"),
            ("Winnebago Chieftain", "Winnebago Chieftain"),
            ("Winnebago Era", "Winnebago Era"),
            ("Winnebago Forza", "Winnebago Forza"),
            ("Winnebago Grand Tour", "Winnebago Grand Tour"),
            ("Winnebago Horizon", "Winnebago Horizon"),
            ("Winnebago Intent", "Winnebago Intent"),
            ("Winnebago Journey", "Winnebago Journey"),
            ("Winnebago Minnie Winnie", "Winnebago Minnie Winnie"),
            ("Winnebago Navion", "Winnebago Navion"),
            ("Winnebago Outlook", "Winnebago Outlook"),
            ("Winnebago Paseo", "Winnebago Paseo"),
            ("Winnebago Revel", "Winnebago Revel"),
            ("Winnebago Sightseer", "Winnebago Sightseer"),
            ("Winnebago Solei", "Winnebago Solei"),
            ("Winnebago Spirit", "Winnebago Spirit"),
            ("Winnebago Sunova", "Winnebago Sunova"),
            ("Winnebago Sunstar", "Winnebago Sunstar"),
            ("Winnebago Tour", "Winnebago Tour"),
            ("Winnebago Travato", "Winnebago Travato"),
            ("Winnebago Trend", "Winnebago Trend"),
            ("Winnebago View", "Winnebago View"),
        ),
    ),
]
Condition = (
    ('New', 'New'),
    ('Local Used', 'Local Used'),
    ('Foriegn Used', 'Foriegn Used'),
)
Steering = (
    ('Right', 'Right'),
    ('Left', 'Left'),
)
Fuels = (
    ('Petrol', 'Petrol'),
    ('Diesel', 'Diesel'),
    ('Electric', 'Electric'),
    ('Solar', 'Solar'),
    ('Hybrid', 'Hybrid'),

)
Transmissions = (
    ('Automatic', 'Automatic'),
    ('Manual', 'Manual'),
    ('Semi Automatic', 'Semi Automatic'),
    ('Continious Variable Transmission', 'Continious Variable Transmission'),

)

Regions = (
   ('VOLTA ',  'VOLTA '),
   ('BRONG AHAFO ',  'BRONG AHAFO '),
   ('OTI ',  'OTI '),
   ('CENTRAL ',  'CENTRAL '),
   ('EASTERN ',  'EASTERN '),
   ('GREATER ACCRA ',  'GREATER ACCRA '),
   ('NORTH EAST ',  'NORTH EAST '),
   ('NORTHERN ',  'NORTHERN '),
   ('SAVANNAH ',  'SAVANNAH '),
   ('UPPER EAST ',  'UPPER EAST '),
   ('UPPER WEST ',  'UPPER WEST '),
   ('WESTERN ',  'WESTERN '),
   ('WESTERN NORTH ',  'WESTERN NORTH '),
   ('BONO EAST  ',  'BONO EAST  '),
   ('AHAFO ',  'AHAFO '),
   ('ASHANTI ',  'ASHANTI '),
)

def car_path(instance, filename):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return os.path.join('car', timestamp, filename)

def car_images_path(instance, filename):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return os.path.join('car_images', timestamp, filename)


class Car(models.Model):
    main_image = models.ImageField(upload_to=car_path)
    description =  models.TextField()
    title =  models.CharField(max_length = 150)
    condition = models.CharField(max_length = 150, choices=Condition)
    makes_and_model = models.CharField(max_length = 150, choices=CarModelsAndMakes)
    mileage = models.PositiveIntegerField()
    location = models.CharField(max_length = 30)
    steering = models.CharField(max_length = 100, choices=Steering)
    color = models.CharField(max_length = 100)
    transmission = models.CharField(max_length = 100, choices=Transmissions)
    fuel = models.CharField(max_length = 100, choices=Fuels)
    interior_color = models.CharField(max_length = 100)
    year_manufactured = YearField()
    registered = models.BooleanField(default=False)
    duty_paid = models.BooleanField(default=False)
    price =  models.DecimalField(decimal_places=2, max_digits=10)
    accessories = models.TextField()
    
    phone_regex = RegexValidator(
        regex=r'^\+?[0-9]{1,3}?\s?\-?[0-9]{1,15}$',
        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed."
    )
    contact_no = models.CharField(validators=[phone_regex], max_length=17, null=True, blank=True) 
    region = models.CharField(max_length=100, choices=Regions)
    slug = models.SlugField(blank=True, null=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    
    def __str__(self):
        return f'{self.makes_and_model} - {self.price}'
    
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.makes_and_model))
        super().save(*args, **kwargs)



class CarImage(models.Model):
    car =  models.ForeignKey(Car, related_name='car_image', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=car_images_path)
    slug = models.SlugField(blank=True, null=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Car Images"

    def __str__(self):
        return f'{self.car.makes_and_model}'
    
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.car.makes_and_model))
        super().save(*args, **kwargs)

 

class CarEnquiry(models.Model):
    car =  models.ForeignKey(Car, related_name='car_enquiry', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    
    phone_regex = RegexValidator(
        regex=r'^\+?[0-9]{1,3}?\s?\-?[0-9]{1,15}$',
        message="Phone number must be entered in the format: '+999 999999999'. Up to 15 digits allowed."
    )
    contact_no = models.CharField(validators=[phone_regex], max_length=17, null=True, blank=True)     
    message = models.TextField()
    slug = models.SlugField(blank=True, null=True, editable=False)
    attended_to = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()

    class Meta:
        verbose_name_plural = "Car Enquires"

    def __str__(self):
        return f'{self.car.makes_and_model}'
    
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.car.makes_and_model))
        super().save(*args, **kwargs)
        
        
        
   